# Generated by Django 6.0.4 on 2026-04-10 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='seeds/')),
                ('description', models.TextField()),
                ('sun_light', models.CharField(max_length=100)),
                ('watering', models.CharField(max_length=100)),
                ('planting_month', models.IntegerField(help_text='Month number from 1 to 12')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seedsmodule.category')),
            ],
        ),
    ]
